package yalla.assignment

class GithubUsers {

    String userName
    Integer githubId
    String avatar_url
    String html_url
    String repos_url
    String type
    String githubName
    String location
    String githubBio
    Integer public_repos
    Date created_at
    Date updated_at

    static constraints = {
        userName nullable: false, blank:false
        githubId nullable: false, blank:false
        avatar_url nullable: true
        html_url nullable: true
        repos_url nullable: true
        type nullable: true
        githubName nullable: true
        location nullable: true
        githubBio nullable: true
        public_repos nullable: true
        created_at nullable: true
        updated_at nullable: true
    }

    // grails will use a human-friendly name instead of an id
    // in the scaffolding autogenerated pages
    String toString(){
        userName
    }
}